package org.dxh.spring.website.mapper.umajin;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.dxh.spring.website.entity.umajin.UserMaster;
import org.dxh.spring.website.entity.umajin.UserMasterDto;
import org.springframework.stereotype.Component;

@Component
public interface UserMasterMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umajin.user_master
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserMasterSqlProvider.class, method="countByExample")
    long countByExample(UserMasterDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umajin.user_master
     *
     * @mbg.generated
     */
    @Delete({
        "delete from umajin.user_master",
        "where user_id = #{user_id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umajin.user_master
     *
     * @mbg.generated
     */
    @Insert({
        "insert into umajin.user_master (user_id, nickname, ",
        "sex, age, birthday, ",
        "regist_date, update_date, ",
        "disable)",
        "values (#{user_id,jdbcType=INTEGER}, #{nickname,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=INTEGER}, #{age,jdbcType=INTEGER}, #{birthday,jdbcType=DATE}, ",
        "#{regist_date,jdbcType=TIMESTAMP}, #{update_date,jdbcType=TIMESTAMP}, ",
        "#{disable,jdbcType=INTEGER})"
    })
    int insert(UserMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umajin.user_master
     *
     * @mbg.generated
     */
    @InsertProvider(type=UserMasterSqlProvider.class, method="insertSelective")
    int insertSelective(UserMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umajin.user_master
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserMasterSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="user_id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.INTEGER),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.DATE),
        @Result(column="regist_date", property="regist_date", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_date", property="update_date", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="disable", property="disable", jdbcType=JdbcType.INTEGER)
    })
    List<UserMaster> selectByExample(UserMasterDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umajin.user_master
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "user_id, nickname, sex, age, birthday, regist_date, update_date, disable",
        "from umajin.user_master",
        "where user_id = #{user_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="user_id", property="user_id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.INTEGER),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.DATE),
        @Result(column="regist_date", property="regist_date", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_date", property="update_date", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="disable", property="disable", jdbcType=JdbcType.INTEGER)
    })
    UserMaster selectByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umajin.user_master
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserMasterSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umajin.user_master
     *
     * @mbg.generated
     */
    @Update({
        "update umajin.user_master",
        "set nickname = #{nickname,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "age = #{age,jdbcType=INTEGER},",
          "birthday = #{birthday,jdbcType=DATE},",
          "regist_date = #{regist_date,jdbcType=TIMESTAMP},",
          "update_date = #{update_date,jdbcType=TIMESTAMP},",
          "disable = #{disable,jdbcType=INTEGER}",
        "where user_id = #{user_id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserMaster record);
}